### ISSUE TITLE
The twitter.py output format correction

### ISSUE THREAD

**Issue by Pritheeev** [Pritheeev/Practice-ML#1]
The twitter.py file is a ML python code to classify the set of tweets based on how positive or how negative they are. As of now, It shows only the polarity of the tweet. Can somebody please, make it into a better understandable binary classifying model as to classify whether the tweet is positive or negative.

**Comment by rajasekar1999** [comment]
Can I work on it? I think I can solve it...

**Comment by Pritheeev** [comment]
Yeah sure... Make sure you give a merge request and not a pull request....

**Comment by rajasekar1999** [comment]
Done @Pritheeev
